name: cvp
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.8.5
  - pip=20.3
  - cudatoolkit=11.3
  - pytorch=1.11.0
  - torchvision=0.12.0
  - numpy=1.19.2
  - pip:
    - Pillow>=7.1.2
    - PyYAML>=5.3.1
    - requests>=2.23.0
    - scipy>=1.4.1
    - tqdm>=4.41.0
    - scikit-learn>=1.1.2
    - scikit-image==0.19.3
    - albumentations==1.2.1
    - opencv-python==4.1.2.30
    - protobuf<4.21.3
    - matplotlib>=3.2.2
    - tensorboard>=2.4.1
    - pandas>=1.1.4
    - seaborn>=0.11.0
    - thop>=0.1.1
    - wandb
    - gdown
    - pycocotools
    - colorama


